GET https://6000-idx-springboot-crud-copilot-1718076077416.cluster-vpxjqdstfzgs6qeiaf7rdlsqrc.cloudworkstations.dev/persona-v1/person/hi?param=ss
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2Nsb3VkLmdvb2dsZS5jb20vd29ya3N0YXRpb25zIiwiYXVkIjoiaWR4LXNwcmluZ2Jvb3QtY3J1ZC1jb3BpbG90LTE3MTgwNzYwNzc0MTYuY2x1c3Rlci12cHhqcWRzdGZ6Z3M2cWVpYWY3cmRsc3FyYy5jbG91ZHdvcmtzdGF0aW9ucy5kZXYiLCJpYXQiOjE3MTgwNzc3MzAsImV4cCI6MTcxODA4MTMzMH0.Ug4vO_P4SB3y8B-C199lGhkFG2-adgjlrbjpCdC066olbVfmu81IhpNHImhipuFCQwKkoUjUVuYjPFBJb41jyjhJDxhY5L8MrYFGM5NNlX5oM-Inem79em4kYug-2kpAGJs9LP5ySiYPwntBkmUd_0Xrv4yhTFxSbttbDd8FWJvrE5uHn7l1WboIxdlTEkZlBsRcYHXmdq2omv9EPzeFcr04fk4orKOLENpZ7WZFGueVMEW0pDb-TBX670qy_zx8_IE3yl9vFl1AebniOi-el-DMo9kH9N0XNWE4eo_3-FYpKBYiBECt2veKPcCyE_b0hoL_sHjwmw6dVYCgwi_GMw