server:
  port: 8084

spring:
  logging:
    level:
      org.hibernate.SQL: DEBUG
  application:
    name: persona-v1
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  webflux:
    base-path: /persona-v1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      show_sql: true
      format_sql: true
      use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

springdoc:
  info:
    version: '0.0.2-SNAPSHOT'
    title: 'persona-v1'
    description: 'Api UX Servicio de pesonas'
    servers:
      - 'http://localhost:6200/'
      - 'http://localhost:8080/'
  api-docs:
    path: /api-docs
    version: "openapi_3_0"
    enabled: true
    yaml:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true