server:
  port: 8080

spring:
  application:
    name: persona-v1
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  webflux:
    base-path: /persona-v1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

springdoc:
  info:
    version: '0.0.2-SNAPSHOT'
    title: 'persona-v1'
    description: 'Api UX Servicio de pesonas'
    servers:
      - 'http://localhost:6200/'
      - 'http://localhost:8080/'
  api-docs:
    path: /openapi
    version: "openapi_3_0"
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true
#    disable-swagger-default-url: true