name: learn-github-action
run-name: ${{ github.actor }}
on: [push]
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.7
            
            - name: Setup Java JDK
              uses: actions/setup-java@v4.2.1
              with: 
                  java-version: 17
                  distribution: temurin
                  cache: maven
            - name: build with maven
              run: |
                  mvn clean install
                  
